import { useState } from 'react'
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Typography,
  Button,
  Box,
  Divider,
  IconButton,
  Snackbar,
  Alert,
  TextField,
} from '@mui/material'
import CloseIcon from '@mui/icons-material/Close'
import ContentCopy from '@mui/icons-material/ContentCopy'

interface Props {
  open: boolean
  name: string
  employeeId: string
  email: string
  temporaryPassword: string
  onClose: () => void
}

function generatePassword(): string {
  const upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  const lower = 'abcdefghijklmnopqrstuvwxyz'
  const digits = '0123456789'
  const special = '@#$&'
  const all = upper + lower + digits
  let pw = ''
  pw += upper[Math.floor(Math.random() * upper.length)]
  pw += lower[Math.floor(Math.random() * lower.length)]
  pw += digits[Math.floor(Math.random() * digits.length)]
  pw += special[Math.floor(Math.random() * special.length)]
  for (let i = 0; i < 4; i++) pw += all[Math.floor(Math.random() * all.length)]
  return pw.split('').sort(() => Math.random() - 0.5).join('')
}

export default function SuccessCredentialsModal({ open, name, employeeId, email, temporaryPassword, onClose }: Props) {
  const password = temporaryPassword || generatePassword()
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [copiedToast, setCopiedToast] = useState(false)

  const copyText = `Employee ID: ${employeeId}
Email: ${email}
Password: ${password}
Login URL: ${window.location.origin}/login`

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(copyText)
      setCopiedToast(true)
    } catch {
      const ta = document.createElement('textarea')
      ta.value = copyText
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
      setCopiedToast(true)
    }
  }

  const handleClose = () => {
    if (!confirmOpen) {
      setConfirmOpen(true)
      return
    }
    setConfirmOpen(false)
    onClose()
  }

  return (
    <>
      <Dialog open={open} maxWidth="sm" fullWidth onClose={handleClose}>
        <DialogTitle sx={{ display: 'flex', alignItems: 'center' }}>
          <Typography variant="h6" sx={{ flexGrow: 1, fontWeight: 600 }}>
            User Created Successfully
          </Typography>
          <IconButton onClick={handleClose} size="small"><CloseIcon /></IconButton>
        </DialogTitle>
        <Divider />
        <DialogContent>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5, mt: 1 }}>
            <Box>
              <Typography variant="caption" sx={{ color: 'text.secondary' }}>Employee</Typography>
              <Typography variant="body1" sx={{ fontWeight: 500 }}>{name}</Typography>
            </Box>
            <Box>
              <Typography variant="caption" sx={{ color: 'text.secondary' }}>Employee ID</Typography>
              <Typography variant="body1" sx={{ fontWeight: 500 }}>{employeeId || 'Generated by system'}</Typography>
            </Box>
            <Box>
              <Typography variant="caption" sx={{ color: 'text.secondary' }}>Email</Typography>
              <Typography variant="body1" sx={{ fontWeight: 500 }}>{email}</Typography>
            </Box>
            <Box>
              <Typography variant="caption" sx={{ color: 'text.secondary' }}>Temporary Password</Typography>
              <Box sx={{ display: 'flex', gap: 1, alignItems: 'center', mt: 0.5 }}>
                <TextField
                  value={password}
                  size="small"
                  slotProps={{ input: { readOnly: true, sx: { fontFamily: 'monospace', fontWeight: 600, fontSize: '0.9rem' } } }}
                  sx={{ flexGrow: 1 }}
                />
                <Button variant="outlined" size="small" startIcon={<ContentCopy />} onClick={handleCopy}>
                  Copy
                </Button>
              </Box>
            </Box>
            {!temporaryPassword && (
              <Typography variant="caption" sx={{ color: 'warning.main', fontStyle: 'italic' }}>
                Please save this password. It will not be shown again.
              </Typography>
            )}
          </Box>
        </DialogContent>
        <Divider />
        <DialogActions sx={{ px: 2, py: 1.5, justifyContent: 'space-between' }}>
          <Button variant="outlined" startIcon={<ContentCopy />} onClick={handleCopy}>
            Copy Credentials
          </Button>
          <Button variant="contained" onClick={handleClose}>
            Close
          </Button>
        </DialogActions>
      </Dialog>

      <Snackbar
        open={copiedToast}
        autoHideDuration={2000}
        onClose={() => setCopiedToast(false)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
      >
        <Alert severity="success" variant="filled">Credentials copied</Alert>
      </Snackbar>

      <Dialog open={confirmOpen} maxWidth="xs" fullWidth onClose={() => setConfirmOpen(false)}>
        <DialogTitle>Have you copied the credentials?</DialogTitle>
        <DialogContent>
          <Typography variant="body2">
            The password will not be shown again after closing.
          </Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setConfirmOpen(false)}>Cancel</Button>
          <Button variant="contained" color="warning" onClick={() => { setConfirmOpen(false); onClose() }}>
            Yes, Close
          </Button>
        </DialogActions>
      </Dialog>
    </>
  )
}
